.Dd 2016-06-14
.Dt sb
.Os
.\" ------------ NAME ------------
.Sh NAME
.Nm sb
\- the server aka 'the core' application of the splonebox network
  analysis tool.

.\" ------------ SYNOBSIS ------------
.Sh SYNOBSIS
.Nm
.Op OPTIONS

.\" ------------ DESCRIPTION ------------
.Sh DESCRIPTION
The
.Nm
is the core application of the splonebox network analysis toolchain. It
orchestrates multiple
.Nm
agents. Each agent consists of at least one plugin. An agent can be
seen as physical network entity while a plugin is an executable which
runs on the agent.

.\" ------------ OPTIONS ------------
.Sh OPTIONS
.Bl -tag -width indent
.It Fl "v, --verbose"
Runs the
.Nm
with verbosity. Increment verbosity with
.Nm -vv
or
.Nm -vvv .

.It Fl "h, --help"
prints help
.It Fl "-version"
returns version

.\" ------------ FILES ------------
.Sh FILES

.Bl -tag -width indent
.It Ev .boxrc
The file to configure the
.Nm
core.

.\" ------------ SEE ALSO ------------
.Sh SEE ALSO

boxrc(1)

.\" ------------ AUTHOR ------------
.Sh AUTHOR
.An "splone" Aq mail@splone.com


