find_package(PkgConfig)
if (PKG_CONFIG_FOUND)
  pkg_check_modules(SHARED_LIBUV REQUIRED libuv)
endif()

find_path(LIBUV_INCLUDE_DIR uv.h
  HINTS ${SHARED_LIBUV_INCLUDEDIR} ${SHARED_LIBUV_INCLUDE_DIRS}
  ${LIMIT_SEARCH})

find_library(LIBUV_LIBRARY NAMES uv
  HINTS ${SHARED_LIBUV_LIBDIR} ${SHARED_LIBUV_LIBRARY_DIRS}
  ${LIMIT_SEARCH})

mark_as_advanced(LIBUV_INCLUDE_DIR LIBUV_LIBRARY)

set(LIBUV_LIBRARIES ${LIBUV_LIBRARY} ${SHARED_LIBUV_LIBRARIES})
set(LIBUV_INCLUDE_DIRS ${LIBUV_INCLUDE_DIR})
