find_package(PkgConfig)
if (PKG_CONFIG_FOUND)
  pkg_check_modules(SHARED_CMOCKA REQUIRED libsodium)
endif()

find_path(CMOCKA_INCLUDE_DIR cmocka.h
  HINTS ${SHARED_CMOCKA_INCLUDEDIR} ${SHARED_CMOCKA_INCLUDE_DIRS}
  ${LIMIT_SEARCH})

find_library(CMOCKA_LIBRARY NAMES cmocka
  HINTS ${SHARED_CMOCKA_LIBDIR} ${SHARED_CMOCKA_LIBRARY_DIRS}
  ${LIMIT_SEARCH})

mark_as_advanced(CMOCKA_INCLUDE_DIR CMOCKA_LIBRARY)

set(CMOCKA_LIBRARIES ${CMOCKA_LIBRARY})
set(CMOCKA_INCLUDE_DIRS ${CMOCKA_INCLUDE_DIR})
