find_package(PkgConfig)
if (PKG_CONFIG_FOUND)
  pkg_check_modules(SHARED_SODIUM REQUIRED libsodium)
endif()

find_path(SODIUM_INCLUDE_DIR sodium.h
  HINTS ${SHARED_SODIUM_INCLUDEDIR} ${SHARED_SODIUM_INCLUDE_DIRS}
  ${LIMIT_SEARCH})

find_library(SODIUM_LIBRARY NAMES sodium
  HINTS ${SHARED_SODIUM_LIBDIR} ${SHARED_SODIUM_LIBRARY_DIRS}
  ${LIMIT_SEARCH})

mark_as_advanced(SODIUM_INCLUDE_DIR SODIUM_LIBRARY)

set(SODIUM_LIBRARIES ${SODIUM_LIBRARY})
set(SODIUM_INCLUDE_DIRS ${SODIUM_INCLUDE_DIR})
