find_package(PkgConfig)
if (PKG_CONFIG_FOUND)
  pkg_check_modules(SHARED_BSD REQUIRED libbsd)
endif()

find_path(BSD_INCLUDE_DIR bsd/bsd.h
  HINTS ${SHARED_BSD_INCLUDEDIR} ${SHARED_BSD_INCLUDE_DIRS}
  ${LIMIT_SEARCH})

find_library(BSD_LIBRARY NAMES bsd
  HINTS ${SHARED_BSD_LIBDIR} ${SHARED_BSD_LIBRARY_DIRS}
  ${LIMIT_SEARCH})

mark_as_advanced(BSD_INCLUDE_DIR BSD_LIBRARY)

set(BSD_LIBRARIES ${BSD_LIBRARY})
set(BSD_INCLUDE_DIRS ${BSD_INCLUDE_DIR})
